name:                slit-scan
version:             0.0.0.0
github:              "flajann2/slit-scan"
license:             MIT
author:              "Fred Mitchell"
maintainer:          "fred.mitchell@kiwelt.de"
copyright:           "2022 Fred Mitchell"

extra-source-files:
- README.pdf
- ChangeLog.org

# Metadata used when publishing your package
synopsis:            Slit Scan command-line implementation.
category:            Graphics, Image Processing

description:         Please see the README PDF on GitHub at <https://github.com/flajann2/slit-scan#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - optparse-applicative
    - hip
    - repa
    - repa-algorithms
    - criterion
    - one-liner
    - hmatrix


executables:
  slit-scan:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - slit-scan
      - optparse-applicative
      - hip
      - repa
      - repa-algorithms
      - criterion
      - unagi-chan

  bench-Hip:
    main:                bench-Hip.hs
    source-dirs:         examples
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - slit-scan
    - hip
    - JuicyPixels
    - JuicyPixels-extra
    - criterion
    - deepseq
    - massiv
    - massiv-io
    - repa
    - repa-algorithms
  
tests:
  slit-scan-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - slit-scan
 
