resolver: lts-19.6

packages:
  - .
extra-deps:
 - hip-1.5.6.0
 - Chart-diagrams-1.9.3
 - SVGFonts-1.7.0.1
 - diagrams-postscript-1.5.1
 - statestack-0.3.1
 - repa-algorithms-3.4.1.5
 - optparse-applicative-0.17.0.0
 - unagi-chan-0.4.1.4
